
title: Tanya Naheta
email: tanyanaheta@example.com
description: >-
  Portfolio for Tanya Naheta, Data Scientist focused on product analytics, strategy, and Responsible AI.
theme: jekyll-theme-minimal

show_downloads: false
google_analytics: 
